// <auto-generated />
using System;
using Comments.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Migrations.Migrations
{
    [DbContext(typeof(CommentsContext))]
    [Migration("20230525153230_ChangeRealtionForFeedback")]
    partial class ChangeRealtionForFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("FeedbackId");

                    b.ToTable("Comments", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("213d4df5-e3f3-4218-8823-a7dc05ea61a8"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 6, 1, 17, 56, 7, 115, DateTimeKind.Local).AddTicks(2533),
                            Text = "omnis",
                            Theme = "optio"
                        },
                        new
                        {
                            ID = new Guid("4af6a591-030f-4623-88d5-8347a416485d"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 7, 30, 21, 22, 50, 142, DateTimeKind.Local).AddTicks(7630),
                            Text = "Sit nesciunt dolorem ratione qui iure.\nDelectus necessitatibus eaque ad.",
                            Theme = "aliquam"
                        },
                        new
                        {
                            ID = new Guid("7b58fcff-054a-47b6-8b80-277efd517596"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2023, 2, 22, 19, 37, 29, 765, DateTimeKind.Local).AddTicks(9093),
                            Text = "Sed debitis est dolores nihil vero ea. Voluptatum doloremque autem. Molestias modi exercitationem saepe voluptatem ut corporis. Hic consequatur vel iste quasi officia et assumenda officiis.",
                            Theme = "eos"
                        },
                        new
                        {
                            ID = new Guid("5e3fda18-9542-4d4a-8cc4-fdad379c0311"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2023, 3, 30, 9, 25, 27, 151, DateTimeKind.Local).AddTicks(9917),
                            Text = "nobis",
                            Theme = "nemo"
                        },
                        new
                        {
                            ID = new Guid("d1bb8ef9-aab4-43ab-a89f-171d9fc3e5e3"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2022, 12, 24, 12, 51, 29, 740, DateTimeKind.Local).AddTicks(1719),
                            Text = "qui",
                            Theme = "nulla"
                        },
                        new
                        {
                            ID = new Guid("5ba48dba-ddbe-4756-84fc-40721b90e925"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 6, 11, 20, 58, 6, 543, DateTimeKind.Local).AddTicks(28),
                            Text = "aliquam",
                            Theme = "velit"
                        },
                        new
                        {
                            ID = new Guid("d0fe831a-2ac0-4964-b99f-618e448758a8"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 7, 18, 13, 56, 54, 907, DateTimeKind.Local).AddTicks(4348),
                            Text = "Sunt nisi neque repellat et velit dolore ducimus.\nAut tempore maiores ut distinctio sit fugit.\nCulpa at magnam consectetur placeat blanditiis.\nOfficiis et aut laboriosam.\nExcepturi ea veritatis error ab numquam.",
                            Theme = "blanditiis"
                        },
                        new
                        {
                            ID = new Guid("1ed4c36d-328b-47e9-95b8-488bcffd1e1f"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2023, 2, 25, 18, 56, 58, 5, DateTimeKind.Local).AddTicks(9487),
                            Text = "Iusto esse officia nihil exercitationem quia.\nQui qui reiciendis repellat est et.\nNam vel harum qui possimus et.\nFuga soluta nisi rem laborum cupiditate hic placeat.\nQui et voluptate ratione quo maiores pariatur.\nSequi esse accusamus est est.",
                            Theme = "vel"
                        },
                        new
                        {
                            ID = new Guid("b9a373bb-ef54-4784-9643-522deaf0c0ae"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2022, 12, 17, 2, 47, 40, 207, DateTimeKind.Local).AddTicks(1338),
                            Text = "facere",
                            Theme = "sit"
                        },
                        new
                        {
                            ID = new Guid("2bd17bf5-d102-4d60-99da-c0978a2b53ba"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2023, 4, 12, 5, 35, 18, 145, DateTimeKind.Local).AddTicks(5296),
                            Text = "Officia error eum et dolores aut aut laudantium minima ex. Dolor et ut non fuga expedita ipsam consequatur. Quidem provident dolorem sint ab. Eaque aut magnam. Rem hic fugit labore quis aspernatur illum. Perspiciatis earum et itaque fugiat enim autem iste laudantium.",
                            Theme = "magni"
                        },
                        new
                        {
                            ID = new Guid("bf2eeaa4-2fdc-49eb-aa14-8ccf4a10dcc9"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2022, 6, 5, 20, 55, 10, 99, DateTimeKind.Local).AddTicks(2415),
                            Text = "officiis",
                            Theme = "eum"
                        },
                        new
                        {
                            ID = new Guid("b7877d18-4103-493f-87aa-15ed6071387c"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 8, 27, 6, 59, 54, 975, DateTimeKind.Local).AddTicks(2822),
                            Text = "Nesciunt in pariatur beatae nostrum quisquam ratione.\nQui aut sequi ipsa esse eaque quas enim exercitationem vitae.\nQuae voluptatum enim minus et odit culpa et vitae iure.\nMaiores perspiciatis dolores earum soluta sit esse aliquid unde illum.\nConsequatur modi qui amet rerum aut est qui.",
                            Theme = "et"
                        },
                        new
                        {
                            ID = new Guid("489638af-43cf-43c5-b460-a8ed51a99f07"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 9, 16, 3, 38, 3, 112, DateTimeKind.Local).AddTicks(8834),
                            Text = "Voluptas distinctio dignissimos.",
                            Theme = "soluta"
                        },
                        new
                        {
                            ID = new Guid("ea18d609-8114-44f5-aa94-41f6d6e47f6f"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 8, 17, 14, 24, 34, 0, DateTimeKind.Local).AddTicks(8928),
                            Text = "Et eaque explicabo ut nisi natus sapiente.\nEnim recusandae ut minima facere explicabo voluptatem.\nNumquam voluptatem quidem adipisci vero.\nAsperiores omnis voluptatem corporis ducimus eos sit sit fugit.\nEnim voluptates provident est error dolor repellat quia aliquam impedit.\nPerferendis perspiciatis eum consequuntur facilis et.",
                            Theme = "fuga"
                        },
                        new
                        {
                            ID = new Guid("dc089c97-35a4-4ddc-aaac-68f57d4859d0"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 11, 23, 10, 58, 50, 952, DateTimeKind.Local).AddTicks(7885),
                            Text = "Nesciunt necessitatibus fuga accusantium et.",
                            Theme = "aut"
                        },
                        new
                        {
                            ID = new Guid("1bd599a3-2731-4bbe-8524-623d8fb740a0"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2022, 6, 5, 17, 28, 21, 744, DateTimeKind.Local).AddTicks(4240),
                            Text = "Ducimus excepturi eum est repellendus ipsam voluptatem vel. Dolores incidunt eveniet. Beatae maxime dolorum fuga. Rem porro minima asperiores autem facilis dolore incidunt qui aut. Qui quos neque magni autem tenetur praesentium. Odit sed asperiores laudantium odit.",
                            Theme = "amet"
                        },
                        new
                        {
                            ID = new Guid("576b3ca9-b530-477d-a765-25d76479cb5d"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2023, 5, 4, 12, 3, 25, 925, DateTimeKind.Local).AddTicks(1955),
                            Text = "Est aperiam commodi sint.\nEst earum facilis a assumenda totam praesentium.\nOdio natus qui doloribus quidem nostrum ex animi reiciendis doloremque.\nEst repudiandae impedit praesentium at consectetur.\nQui voluptate magnam itaque qui ea ratione optio.\nSequi dolorem et quam mollitia iure ducimus.",
                            Theme = "eum"
                        },
                        new
                        {
                            ID = new Guid("e70060dc-d57b-4eb9-82c9-83aced0e28d9"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2023, 5, 9, 0, 29, 22, 546, DateTimeKind.Local).AddTicks(117),
                            Text = "Temporibus nihil ipsum corrupti voluptatem omnis officiis et velit. Nulla facilis aperiam inventore nihil sequi repellat debitis dolor nobis. Qui ullam placeat dolorem esse sit mollitia alias sunt voluptatibus. Adipisci molestiae vel rerum maiores. Vel facilis et officia saepe doloremque ipsa.",
                            Theme = "consequatur"
                        },
                        new
                        {
                            ID = new Guid("bbeaa05b-ef78-413e-9ea7-95cf760bbb6c"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2022, 6, 5, 19, 31, 46, 773, DateTimeKind.Local).AddTicks(2763),
                            Text = "Ut quo dolorem voluptates labore aut tempore.\nAssumenda sed labore ut quod eius aut assumenda corporis quisquam.\nMagnam repudiandae sapiente eum nostrum maiores explicabo beatae molestias.\nLaboriosam saepe voluptates inventore omnis delectus ut quia numquam qui.\nVoluptate temporibus temporibus.\nRepellendus labore dolorem facilis quo fugiat animi.",
                            Theme = "nobis"
                        },
                        new
                        {
                            ID = new Guid("f9047885-c25a-475d-b1e2-7899c22c5c6a"),
                            FeedbackId = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            PostDate = new DateTime(2023, 4, 11, 23, 47, 2, 183, DateTimeKind.Local).AddTicks(7036),
                            Text = "Ut perspiciatis in quia iure.",
                            Theme = "reprehenderit"
                        },
                        new
                        {
                            ID = new Guid("c1b8d33f-4517-4be9-aec3-9e0818070cd5"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 10, 29, 8, 55, 57, 670, DateTimeKind.Local).AddTicks(3593),
                            Text = "Minus vel suscipit quo laboriosam.",
                            Theme = "molestiae"
                        },
                        new
                        {
                            ID = new Guid("a3efc9b3-5e17-47ec-8442-eaff025447d8"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2023, 2, 26, 18, 14, 7, 637, DateTimeKind.Local).AddTicks(506),
                            Text = "Consequatur nihil quis consequuntur sed sed qui ipsam.",
                            Theme = "recusandae"
                        },
                        new
                        {
                            ID = new Guid("8d828728-356d-484f-9b35-bfd6c4af4e16"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 11, 14, 15, 3, 40, 918, DateTimeKind.Local).AddTicks(5193),
                            Text = "Ab non eos explicabo corporis ut possimus. In nemo voluptas nam ea consequuntur enim ut aspernatur. Amet dignissimos qui sunt. Cupiditate repellat eius vel ut nemo et non iusto eaque.",
                            Theme = "aut"
                        },
                        new
                        {
                            ID = new Guid("97bfdf74-5501-4ee1-9321-9888ea07a3bc"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 12, 23, 18, 39, 34, 454, DateTimeKind.Local).AddTicks(2284),
                            Text = "Nam quo aut est dolore. Dicta dolores perspiciatis rerum voluptatem. Id dicta voluptatibus libero aliquid molestiae. Expedita molestiae voluptatum officia neque qui ea totam. Suscipit et ut repellat est enim voluptas cum quo id.",
                            Theme = "sint"
                        },
                        new
                        {
                            ID = new Guid("15e48967-ed7b-4e5d-a321-77590de6537c"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 11, 16, 10, 28, 59, 267, DateTimeKind.Local).AddTicks(5748),
                            Text = "Laborum vel doloribus et nesciunt impedit iste vitae.",
                            Theme = "fugiat"
                        },
                        new
                        {
                            ID = new Guid("bbeb8304-87e9-496e-9c45-986b04711b20"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2023, 2, 27, 4, 57, 18, 590, DateTimeKind.Local).AddTicks(6335),
                            Text = "ab",
                            Theme = "et"
                        },
                        new
                        {
                            ID = new Guid("bf172b85-cbea-498e-a0ba-7c35d6efeeb5"),
                            FeedbackId = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            PostDate = new DateTime(2022, 8, 16, 21, 37, 31, 578, DateTimeKind.Local).AddTicks(63),
                            Text = "et",
                            Theme = "perferendis"
                        },
                        new
                        {
                            ID = new Guid("895b8b28-17d9-4a8b-952d-b7245e004e1d"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2022, 10, 21, 11, 15, 25, 887, DateTimeKind.Local).AddTicks(7006),
                            Text = "Maxime perspiciatis dolores.",
                            Theme = "dolore"
                        },
                        new
                        {
                            ID = new Guid("b2e61069-1a39-467e-a2eb-ebf97a653413"),
                            FeedbackId = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            PostDate = new DateTime(2022, 10, 16, 2, 16, 59, 934, DateTimeKind.Local).AddTicks(3216),
                            Text = "inventore",
                            Theme = "sit"
                        },
                        new
                        {
                            ID = new Guid("c61e53c9-0f4a-4c03-bce1-b422c40f0ca8"),
                            FeedbackId = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            PostDate = new DateTime(2022, 10, 28, 2, 43, 38, 362, DateTimeKind.Local).AddTicks(2137),
                            Text = "Velit vel non consectetur aut sit excepturi. Quia excepturi odit distinctio aut est maxime. Ipsam nam quibusdam voluptatem voluptatem error. Officia dicta qui qui occaecati. Perferendis et rerum rerum laboriosam.",
                            Theme = "deleniti"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeedbackTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Feedbacks", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("d0f1c668-d17d-43f6-b06f-57b4462939c7"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("d7725adf-ba7d-4d7a-9ff6-9ae41c7e4d76"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("4669df4c-b2b0-4702-bc02-50e6f9ab9de6"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("ba864a71-55a7-4ea8-868a-4a000b0422da"),
                            FeedbackTheme = "Suggestion"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("CommentId");

                    b.ToTable("Replies", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f6102b09-1e2f-4306-bf16-ff0fa400146d"),
                            CommentId = new Guid("213d4df5-e3f3-4218-8823-a7dc05ea61a8"),
                            PostDate = new DateTime(2023, 4, 6, 21, 57, 14, 836, DateTimeKind.Local).AddTicks(7958),
                            Text = "Non qui unde officia voluptas maiores eos."
                        },
                        new
                        {
                            ID = new Guid("1f1c34c4-331b-478c-b3b5-cd5c486faf27"),
                            CommentId = new Guid("4af6a591-030f-4623-88d5-8347a416485d"),
                            PostDate = new DateTime(2022, 12, 1, 16, 44, 8, 26, DateTimeKind.Local).AddTicks(4060),
                            Text = "Adipisci ipsam nihil magnam. Laudantium dolore eos iusto autem deserunt eius ad explicabo est. Enim officiis pariatur est voluptatem. Est asperiores recusandae ipsum. Inventore molestias aut dicta illo possimus eos."
                        },
                        new
                        {
                            ID = new Guid("f92ddac9-7efb-4ab0-ad44-aef3ef86c4c1"),
                            CommentId = new Guid("7b58fcff-054a-47b6-8b80-277efd517596"),
                            PostDate = new DateTime(2023, 3, 9, 14, 40, 15, 461, DateTimeKind.Local).AddTicks(6128),
                            Text = "Et dolorem consequatur commodi velit eaque voluptatem sit ea.\nBlanditiis magni excepturi in.\nQuia explicabo explicabo similique recusandae.\nDignissimos nihil laboriosam sed nihil consequuntur officia optio amet."
                        },
                        new
                        {
                            ID = new Guid("d5daa88f-065d-459e-8d63-6d6ce71e1414"),
                            CommentId = new Guid("5e3fda18-9542-4d4a-8cc4-fdad379c0311"),
                            PostDate = new DateTime(2022, 7, 29, 18, 33, 53, 774, DateTimeKind.Local).AddTicks(9557),
                            Text = "accusantium"
                        },
                        new
                        {
                            ID = new Guid("c240b9a1-8271-47b3-a581-9a0312ba70c2"),
                            CommentId = new Guid("d1bb8ef9-aab4-43ab-a89f-171d9fc3e5e3"),
                            PostDate = new DateTime(2022, 8, 26, 18, 5, 33, 54, DateTimeKind.Local).AddTicks(8193),
                            Text = "Quia et quia et quasi ad libero distinctio sint."
                        },
                        new
                        {
                            ID = new Guid("d728d6b1-89d3-4283-86a8-8eb617968a9b"),
                            CommentId = new Guid("5ba48dba-ddbe-4756-84fc-40721b90e925"),
                            PostDate = new DateTime(2023, 2, 11, 22, 49, 12, 67, DateTimeKind.Local).AddTicks(9434),
                            Text = "Odio voluptatem quibusdam.\nQuis et velit earum sint aperiam.\nAtque deserunt totam.\nConsequatur nesciunt incidunt aliquid voluptatem saepe ut quia aliquam.\nDoloribus qui dolor."
                        },
                        new
                        {
                            ID = new Guid("74c64464-3eb3-4d85-b98a-bdfc24fb4437"),
                            CommentId = new Guid("d0fe831a-2ac0-4964-b99f-618e448758a8"),
                            PostDate = new DateTime(2022, 6, 22, 2, 55, 13, 360, DateTimeKind.Local).AddTicks(64),
                            Text = "Similique mollitia ut corporis est et aut. Deserunt rerum nobis nobis sed voluptatibus est officiis. Vel quae dolores. Nostrum incidunt possimus et et."
                        },
                        new
                        {
                            ID = new Guid("98ccffb3-3bf9-4890-8e71-afa37badcfe7"),
                            CommentId = new Guid("1ed4c36d-328b-47e9-95b8-488bcffd1e1f"),
                            PostDate = new DateTime(2022, 11, 18, 20, 11, 19, 30, DateTimeKind.Local).AddTicks(5238),
                            Text = "voluptatibus"
                        },
                        new
                        {
                            ID = new Guid("b52a4e60-d80d-497c-813a-fed1df055d91"),
                            CommentId = new Guid("b9a373bb-ef54-4784-9643-522deaf0c0ae"),
                            PostDate = new DateTime(2023, 4, 21, 20, 40, 10, 88, DateTimeKind.Local).AddTicks(2562),
                            Text = "Sapiente voluptate esse est ducimus velit dolor."
                        },
                        new
                        {
                            ID = new Guid("2736375f-2d15-4abf-89d6-bbaeb7575b94"),
                            CommentId = new Guid("2bd17bf5-d102-4d60-99da-c0978a2b53ba"),
                            PostDate = new DateTime(2022, 10, 9, 0, 36, 5, 876, DateTimeKind.Local).AddTicks(4712),
                            Text = "Debitis non omnis ea doloribus."
                        },
                        new
                        {
                            ID = new Guid("3eb6b5e2-f602-4d49-a97b-35d931987e82"),
                            CommentId = new Guid("bf2eeaa4-2fdc-49eb-aa14-8ccf4a10dcc9"),
                            PostDate = new DateTime(2023, 5, 9, 10, 8, 44, 388, DateTimeKind.Local).AddTicks(5568),
                            Text = "Dolor exercitationem aspernatur quo repellat quia facere aut omnis. In consequatur voluptatum. Dolorem ut itaque id dicta ipsa. Quod a cupiditate ut earum temporibus magnam. Accusantium sit amet. Esse in dolore."
                        },
                        new
                        {
                            ID = new Guid("346421bc-ca35-4abe-bee1-6b74f58be2a8"),
                            CommentId = new Guid("b7877d18-4103-493f-87aa-15ed6071387c"),
                            PostDate = new DateTime(2022, 7, 8, 10, 45, 18, 331, DateTimeKind.Local).AddTicks(7737),
                            Text = "Voluptatum autem dolor sit molestiae sapiente dolores omnis ut.\nLaborum ut distinctio accusamus ipsum pariatur mollitia modi corporis.\nSimilique neque quos repudiandae.\nUt omnis quia deleniti culpa ut.\nSoluta veritatis magnam.\nOdio et neque vero repellat quibusdam ex quis ut."
                        },
                        new
                        {
                            ID = new Guid("6e019b9b-683e-46ec-9951-32e648e5a090"),
                            CommentId = new Guid("489638af-43cf-43c5-b460-a8ed51a99f07"),
                            PostDate = new DateTime(2022, 10, 1, 17, 44, 21, 393, DateTimeKind.Local).AddTicks(8811),
                            Text = "Commodi eius a et quibusdam itaque ea quo possimus.\nDolorum rerum dolor quos.\nAut iusto est tenetur molestiae aut excepturi qui iure."
                        },
                        new
                        {
                            ID = new Guid("e69c31bd-f613-4db0-ba82-914300bc36c5"),
                            CommentId = new Guid("ea18d609-8114-44f5-aa94-41f6d6e47f6f"),
                            PostDate = new DateTime(2023, 4, 8, 22, 11, 11, 841, DateTimeKind.Local).AddTicks(9365),
                            Text = "Incidunt veniam et sunt. Nemo error assumenda et et. Quas vel quasi rem est nesciunt quasi. Omnis repudiandae vel facilis debitis nam voluptate. Sit deserunt maxime qui dicta."
                        },
                        new
                        {
                            ID = new Guid("9e9160c0-ac53-4766-af24-4057be9be7e3"),
                            CommentId = new Guid("dc089c97-35a4-4ddc-aaac-68f57d4859d0"),
                            PostDate = new DateTime(2022, 11, 20, 0, 38, 49, 950, DateTimeKind.Local).AddTicks(4330),
                            Text = "doloremque"
                        },
                        new
                        {
                            ID = new Guid("03d3cfe0-b42e-4033-9ca0-0f1e2cb18a65"),
                            CommentId = new Guid("1bd599a3-2731-4bbe-8524-623d8fb740a0"),
                            PostDate = new DateTime(2023, 3, 15, 20, 25, 0, 2, DateTimeKind.Local).AddTicks(1192),
                            Text = "Alias molestiae reprehenderit aspernatur.\nVelit est dolore doloribus aut iure molestias aut eum sint.\nOfficiis eius explicabo nesciunt quod esse quia architecto molestiae eveniet.\nDolor qui rerum recusandae fugit enim corrupti harum assumenda.\nEt et ut voluptatem aut ut totam sed.\nIpsam doloremque delectus sit ut et."
                        },
                        new
                        {
                            ID = new Guid("142a4c7b-dafc-4cd0-9de7-79f4176cc8a3"),
                            CommentId = new Guid("576b3ca9-b530-477d-a765-25d76479cb5d"),
                            PostDate = new DateTime(2023, 3, 13, 22, 0, 46, 610, DateTimeKind.Local).AddTicks(8715),
                            Text = "omnis"
                        },
                        new
                        {
                            ID = new Guid("f04793d6-2899-4790-a0fa-84a9dabd6af3"),
                            CommentId = new Guid("e70060dc-d57b-4eb9-82c9-83aced0e28d9"),
                            PostDate = new DateTime(2023, 4, 3, 13, 29, 42, 140, DateTimeKind.Local).AddTicks(2830),
                            Text = "accusamus"
                        },
                        new
                        {
                            ID = new Guid("c64f7c35-c404-4ac7-9f95-468f535bb74f"),
                            CommentId = new Guid("bbeaa05b-ef78-413e-9ea7-95cf760bbb6c"),
                            PostDate = new DateTime(2022, 8, 6, 19, 40, 18, 554, DateTimeKind.Local).AddTicks(3180),
                            Text = "commodi"
                        },
                        new
                        {
                            ID = new Guid("4820206e-1cbf-4098-9b60-56cc99a8b753"),
                            CommentId = new Guid("f9047885-c25a-475d-b1e2-7899c22c5c6a"),
                            PostDate = new DateTime(2022, 10, 19, 0, 26, 28, 243, DateTimeKind.Local).AddTicks(5455),
                            Text = "nobis"
                        },
                        new
                        {
                            ID = new Guid("eb2562d5-336d-4e24-bdf7-5360085bdf42"),
                            CommentId = new Guid("c1b8d33f-4517-4be9-aec3-9e0818070cd5"),
                            PostDate = new DateTime(2022, 11, 3, 19, 46, 2, 753, DateTimeKind.Local).AddTicks(5368),
                            Text = "Maiores ratione voluptas dicta similique sint vero."
                        },
                        new
                        {
                            ID = new Guid("4e5e765d-05b7-450d-9c78-0d5bd48776a4"),
                            CommentId = new Guid("a3efc9b3-5e17-47ec-8442-eaff025447d8"),
                            PostDate = new DateTime(2023, 2, 11, 23, 50, 58, 895, DateTimeKind.Local).AddTicks(4303),
                            Text = "voluptatum"
                        },
                        new
                        {
                            ID = new Guid("923e9cc6-d68c-4244-880e-9a81326b4570"),
                            CommentId = new Guid("8d828728-356d-484f-9b35-bfd6c4af4e16"),
                            PostDate = new DateTime(2023, 5, 7, 10, 23, 9, 895, DateTimeKind.Local).AddTicks(5016),
                            Text = "Et illo quam perferendis enim quia voluptatem corporis nulla."
                        },
                        new
                        {
                            ID = new Guid("4eab761b-860b-407d-a56e-6b66f1c57f5b"),
                            CommentId = new Guid("97bfdf74-5501-4ee1-9321-9888ea07a3bc"),
                            PostDate = new DateTime(2023, 3, 13, 3, 30, 5, 347, DateTimeKind.Local).AddTicks(7697),
                            Text = "qui"
                        },
                        new
                        {
                            ID = new Guid("d41c3c73-4920-448c-9707-82c3a5e3926b"),
                            CommentId = new Guid("15e48967-ed7b-4e5d-a321-77590de6537c"),
                            PostDate = new DateTime(2022, 11, 30, 8, 33, 16, 882, DateTimeKind.Local).AddTicks(5928),
                            Text = "Fugiat laborum consequuntur assumenda dolores harum necessitatibus non libero.\nExcepturi reprehenderit eum distinctio dolorem magnam dolorem tempora facere atque.\nFacere ipsam exercitationem tempora sunt sunt quae.\nMagnam maiores autem esse nesciunt dignissimos.\nOccaecati voluptatem et aspernatur ad reprehenderit consequatur eum dolores."
                        },
                        new
                        {
                            ID = new Guid("40644db0-f8d4-4e87-943e-eed33256c825"),
                            CommentId = new Guid("bbeb8304-87e9-496e-9c45-986b04711b20"),
                            PostDate = new DateTime(2023, 3, 8, 5, 48, 34, 262, DateTimeKind.Local).AddTicks(6032),
                            Text = "Sit quibusdam architecto.\nReiciendis vel hic veniam ut corporis unde voluptatum.\nDignissimos autem id sed distinctio."
                        },
                        new
                        {
                            ID = new Guid("b538f6b9-b19b-4053-b499-da794a88fdb1"),
                            CommentId = new Guid("bf172b85-cbea-498e-a0ba-7c35d6efeeb5"),
                            PostDate = new DateTime(2023, 4, 18, 23, 42, 4, 986, DateTimeKind.Local).AddTicks(8328),
                            Text = "odit"
                        },
                        new
                        {
                            ID = new Guid("afa6f096-db70-436a-84f5-3da975786510"),
                            CommentId = new Guid("895b8b28-17d9-4a8b-952d-b7245e004e1d"),
                            PostDate = new DateTime(2022, 12, 25, 0, 25, 27, 103, DateTimeKind.Local).AddTicks(644),
                            Text = "Expedita quis qui alias impedit unde commodi totam."
                        },
                        new
                        {
                            ID = new Guid("80ca66a7-4a43-4dc5-b2e9-9d83aeac89e0"),
                            CommentId = new Guid("b2e61069-1a39-467e-a2eb-ebf97a653413"),
                            PostDate = new DateTime(2022, 5, 29, 12, 24, 36, 322, DateTimeKind.Local).AddTicks(7569),
                            Text = "est"
                        },
                        new
                        {
                            ID = new Guid("a091e439-1f3e-475f-8f88-ba61cf56cf65"),
                            CommentId = new Guid("c61e53c9-0f4a-4c03-bce1-b422c40f0ca8"),
                            PostDate = new DateTime(2023, 3, 10, 10, 8, 24, 904, DateTimeKind.Local).AddTicks(8436),
                            Text = "consequuntur"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.HasOne("Comments.Data.Models.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.HasOne("Comments.Data.Models.Comment", "Comment")
                        .WithMany("Replies")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
