// <auto-generated />
using System;
using Comments.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Migrations.Migrations
{
    [DbContext(typeof(CommentsContext))]
    [Migration("20230525153834_ChangePropsNames")]
    partial class ChangePropsNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentFeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentPostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentTheme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("CommentFeedbackId");

                    b.ToTable("Comments", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b6b45b44-7102-4414-ac51-cc502adeb873"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2022, 6, 2, 22, 4, 7, 186, DateTimeKind.Local).AddTicks(2565),
                            CommentText = "ad",
                            CommentTheme = "iure"
                        },
                        new
                        {
                            ID = new Guid("a596c921-9a75-4bee-8d07-8fc558411501"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2023, 5, 10, 13, 16, 47, 993, DateTimeKind.Local).AddTicks(5560),
                            CommentText = "Eum veritatis at molestias ducimus doloremque sed rerum aspernatur amet. Sint nihil eum placeat aut. Hic voluptatibus sit qui quis consequatur ut. Illum nobis modi culpa unde fugit sed eaque consectetur adipisci. Dolorum quam vel modi autem.",
                            CommentTheme = "facere"
                        },
                        new
                        {
                            ID = new Guid("9aa6e95e-bc99-4ffb-bc78-62e6feab399b"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2023, 2, 10, 17, 24, 1, 994, DateTimeKind.Local).AddTicks(9568),
                            CommentText = "temporibus",
                            CommentTheme = "a"
                        },
                        new
                        {
                            ID = new Guid("6e9318f8-1fe8-45ab-b519-ccbb23c73818"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 9, 9, 3, 29, 36, 684, DateTimeKind.Local).AddTicks(477),
                            CommentText = "Aperiam soluta dolor hic maiores laboriosam non quasi eos vel. Distinctio et adipisci molestias molestiae in amet fuga consequatur est. Similique deleniti iusto odit. Illo in et. Pariatur perferendis optio. Eos debitis nemo culpa.",
                            CommentTheme = "nostrum"
                        },
                        new
                        {
                            ID = new Guid("31a55e74-e566-4302-92e4-77b34240637e"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2023, 4, 1, 11, 57, 30, 628, DateTimeKind.Local).AddTicks(5059),
                            CommentText = "doloremque",
                            CommentTheme = "pariatur"
                        },
                        new
                        {
                            ID = new Guid("034dcfe2-f065-4e26-b0d3-8ef3dc29ba50"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 8, 15, 23, 11, 47, 90, DateTimeKind.Local).AddTicks(1527),
                            CommentText = "Ducimus ipsa nemo hic accusamus. Placeat ullam dolorem et autem id. Sed amet quis hic ut sunt alias nihil.",
                            CommentTheme = "in"
                        },
                        new
                        {
                            ID = new Guid("cd368a36-f4da-4b1b-9ce7-2fc2ace6dcc0"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 9, 30, 14, 10, 45, 600, DateTimeKind.Local).AddTicks(5619),
                            CommentText = "Minima quo dicta cumque qui.\nSunt similique amet voluptates eos voluptatum adipisci.",
                            CommentTheme = "voluptates"
                        },
                        new
                        {
                            ID = new Guid("6c927d62-9b0b-4e94-b0ea-ea2f6f2178c8"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2022, 8, 3, 8, 45, 30, 715, DateTimeKind.Local).AddTicks(3177),
                            CommentText = "Deleniti dolores eum.\nEos qui qui et dolores et ducimus labore dolores.\nQui quas vitae perferendis commodi id.\nQuo dolorum expedita reprehenderit expedita molestias at sint.\nMaiores voluptate similique atque id maiores.",
                            CommentTheme = "fugiat"
                        },
                        new
                        {
                            ID = new Guid("ca01b1cf-a0dc-4611-b6bc-77c51afbb255"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 8, 19, 18, 7, 47, 467, DateTimeKind.Local).AddTicks(142),
                            CommentText = "modi",
                            CommentTheme = "commodi"
                        },
                        new
                        {
                            ID = new Guid("589cbd4c-ce46-4139-bd08-72bdb764de9c"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2022, 7, 31, 21, 48, 2, 920, DateTimeKind.Local).AddTicks(7459),
                            CommentText = "Sequi ut sint magnam et.",
                            CommentTheme = "molestiae"
                        },
                        new
                        {
                            ID = new Guid("81923ef3-6adb-4d51-aace-d671a0382227"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2022, 10, 24, 18, 53, 24, 498, DateTimeKind.Local).AddTicks(4140),
                            CommentText = "impedit",
                            CommentTheme = "quia"
                        },
                        new
                        {
                            ID = new Guid("5610e6ef-282c-4be1-828c-57b0b5202d33"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2022, 11, 3, 12, 11, 32, 137, DateTimeKind.Local).AddTicks(8207),
                            CommentText = "Dolorem quia iusto cumque blanditiis.",
                            CommentTheme = "facilis"
                        },
                        new
                        {
                            ID = new Guid("4c4e7eef-ea3e-41ac-bf5a-255a89d7a632"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 6, 24, 15, 45, 20, 621, DateTimeKind.Local).AddTicks(3013),
                            CommentText = "Rem ea adipisci animi et facere placeat non et. Dolorem praesentium repellendus tenetur magnam. Repellat dolorum itaque doloremque doloremque blanditiis odit aut nostrum qui. Aut eos deserunt occaecati in commodi pariatur cumque. Minima iusto officia voluptatem ut voluptas.",
                            CommentTheme = "minima"
                        },
                        new
                        {
                            ID = new Guid("924cc7ef-791b-4abe-8665-c914c6de51ba"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2023, 2, 14, 16, 30, 15, 52, DateTimeKind.Local).AddTicks(4387),
                            CommentText = "Voluptate labore unde sint.\nAccusantium rerum quia.\nQuia excepturi aliquam distinctio deserunt qui optio.\nUllam officia adipisci.\nId voluptas eum tempore beatae sed sapiente itaque sit asperiores.\nEt adipisci sed expedita nulla facere quis officiis voluptatem.",
                            CommentTheme = "et"
                        },
                        new
                        {
                            ID = new Guid("516eab17-30f1-401d-af6e-8992f666354e"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 7, 25, 22, 3, 18, 727, DateTimeKind.Local).AddTicks(8503),
                            CommentText = "Aut nesciunt aut. Qui voluptatibus sed possimus in ut et deleniti. Magnam itaque corrupti ducimus dignissimos possimus doloremque voluptatem sapiente dolorem. Cum consequatur neque magnam quia sit voluptatem harum. Iure nihil atque. Dolor unde illum expedita reprehenderit rem voluptatem vitae non hic.",
                            CommentTheme = "est"
                        },
                        new
                        {
                            ID = new Guid("4ae7e910-ed61-4852-a80c-e7cd955c5f89"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2022, 10, 10, 20, 6, 15, 971, DateTimeKind.Local).AddTicks(39),
                            CommentText = "Et omnis qui aut exercitationem doloribus nemo nostrum est deserunt. In provident aspernatur et. Soluta sit odit.",
                            CommentTheme = "eum"
                        },
                        new
                        {
                            ID = new Guid("18611973-ae6e-43e8-bf4d-4a094c88f1ba"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2022, 8, 23, 5, 24, 43, 257, DateTimeKind.Local).AddTicks(8790),
                            CommentText = "Consequatur voluptatem eum.\nQui incidunt tempora.\nOptio aspernatur quasi rerum atque laborum.\nUt perspiciatis dicta.",
                            CommentTheme = "fuga"
                        },
                        new
                        {
                            ID = new Guid("ca52595c-706d-4596-816a-e3c5e6d21543"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2023, 4, 19, 1, 7, 11, 949, DateTimeKind.Local).AddTicks(6356),
                            CommentText = "Qui quasi nostrum optio sequi dolorum quam dolorem occaecati illum.",
                            CommentTheme = "adipisci"
                        },
                        new
                        {
                            ID = new Guid("7b632433-ca6d-421d-b3ab-e1daeb6ca005"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 6, 17, 6, 10, 22, 556, DateTimeKind.Local).AddTicks(8798),
                            CommentText = "Et et et distinctio amet similique quibusdam. Laboriosam ut eius autem quia. Vitae dolor culpa modi magni corporis id.",
                            CommentTheme = "placeat"
                        },
                        new
                        {
                            ID = new Guid("48c954de-ae23-4759-98fb-0c124bfadc87"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2023, 3, 9, 23, 29, 12, 201, DateTimeKind.Local).AddTicks(4050),
                            CommentText = "Qui rerum nesciunt necessitatibus qui velit culpa.",
                            CommentTheme = "cupiditate"
                        },
                        new
                        {
                            ID = new Guid("1323d20a-3bfe-4088-9296-2a20e8028bbc"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 8, 5, 0, 2, 11, 538, DateTimeKind.Local).AddTicks(5147),
                            CommentText = "Debitis aperiam officia. Sit corrupti accusantium. Alias eum illo illo eos ut accusamus.",
                            CommentTheme = "modi"
                        },
                        new
                        {
                            ID = new Guid("18d81b75-378c-4daa-ba68-e3ce723ae502"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2023, 5, 19, 1, 17, 23, 166, DateTimeKind.Local).AddTicks(7214),
                            CommentText = "Natus corporis aut veritatis in sed ea et mollitia.\nConsequatur ut inventore labore.\nEnim eligendi soluta dolor.\nUt amet sed animi deleniti corporis fuga.\nTemporibus ex id dignissimos.",
                            CommentTheme = "numquam"
                        },
                        new
                        {
                            ID = new Guid("8c12089f-173f-4012-993b-1088798c4990"),
                            CommentFeedbackId = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            CommentPostDate = new DateTime(2022, 7, 18, 0, 55, 24, 422, DateTimeKind.Local).AddTicks(9236),
                            CommentText = "Voluptatum vel vero dolor quam beatae sed enim.\nEt eligendi at optio vitae.\nPerferendis et ex commodi sed.\nAspernatur illum asperiores sed.\nEa error quam culpa distinctio corporis sed quo a.",
                            CommentTheme = "a"
                        },
                        new
                        {
                            ID = new Guid("47cdaa48-c1b6-46b2-a7f2-4781d581da0f"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2022, 7, 9, 6, 41, 42, 464, DateTimeKind.Local).AddTicks(3651),
                            CommentText = "ipsum",
                            CommentTheme = "ut"
                        },
                        new
                        {
                            ID = new Guid("a29535b5-405e-4d16-b70f-89a270c242c0"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2023, 2, 12, 12, 35, 31, 164, DateTimeKind.Local).AddTicks(9131),
                            CommentText = "Voluptates doloremque ipsa ut.",
                            CommentTheme = "quia"
                        },
                        new
                        {
                            ID = new Guid("47f55c4b-65bc-43cd-a450-10202006338d"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 9, 12, 18, 32, 5, 851, DateTimeKind.Local).AddTicks(4316),
                            CommentText = "Est exercitationem ipsum.",
                            CommentTheme = "eveniet"
                        },
                        new
                        {
                            ID = new Guid("df7fb061-24db-474f-9748-6eda40e83412"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 12, 14, 17, 30, 42, 945, DateTimeKind.Local).AddTicks(8647),
                            CommentText = "et",
                            CommentTheme = "exercitationem"
                        },
                        new
                        {
                            ID = new Guid("d0ef0f9c-bedf-422f-867e-e412fadb26ea"),
                            CommentFeedbackId = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            CommentPostDate = new DateTime(2022, 8, 22, 20, 21, 51, 870, DateTimeKind.Local).AddTicks(6167),
                            CommentText = "consequatur",
                            CommentTheme = "eos"
                        },
                        new
                        {
                            ID = new Guid("78e5172e-edcf-4a33-a68e-3c882e3ace28"),
                            CommentFeedbackId = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            CommentPostDate = new DateTime(2023, 3, 24, 7, 15, 26, 669, DateTimeKind.Local).AddTicks(1967),
                            CommentText = "dolorum",
                            CommentTheme = "quae"
                        },
                        new
                        {
                            ID = new Guid("51165c35-e1eb-41c9-965a-045c4bf6dec3"),
                            CommentFeedbackId = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            CommentPostDate = new DateTime(2022, 10, 4, 16, 4, 32, 899, DateTimeKind.Local).AddTicks(6893),
                            CommentText = "Modi et ipsum ea voluptatum quisquam.",
                            CommentTheme = "tempora"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeedbackTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Feedbacks", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("9fa263eb-e0ca-4646-aef8-74f9f5fdb9c4"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("150f1b18-1fe9-4f5e-b48b-bf7d02305cfb"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("e1d62422-5618-492e-bb0e-d1193f020ea2"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("9b79c8b2-45c1-498e-802c-45730ed91181"),
                            FeedbackTheme = "Suggestion"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReplyCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReplyPostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("ReplyCommentId");

                    b.ToTable("Replies", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b3a150f6-4aec-4e88-8598-52665bdb6a19"),
                            ReplyCommentId = new Guid("b6b45b44-7102-4414-ac51-cc502adeb873"),
                            ReplyPostDate = new DateTime(2022, 8, 16, 20, 17, 46, 274, DateTimeKind.Local).AddTicks(8878),
                            ReplyText = "Et doloremque fugiat placeat voluptatem minima minima quos sapiente nihil."
                        },
                        new
                        {
                            ID = new Guid("d6d0f0bc-5f7f-4ed3-a49b-fba650bee247"),
                            ReplyCommentId = new Guid("a596c921-9a75-4bee-8d07-8fc558411501"),
                            ReplyPostDate = new DateTime(2022, 10, 28, 8, 21, 14, 745, DateTimeKind.Local).AddTicks(9012),
                            ReplyText = "Modi et omnis est ut vel sit veniam alias.\nEa sit sunt et error sequi perspiciatis.\nLaudantium sit repellendus quidem veniam est itaque voluptatum ut excepturi."
                        },
                        new
                        {
                            ID = new Guid("f75a9e8d-f9ca-48dc-8554-22a5a10db64c"),
                            ReplyCommentId = new Guid("9aa6e95e-bc99-4ffb-bc78-62e6feab399b"),
                            ReplyPostDate = new DateTime(2023, 5, 3, 4, 48, 51, 952, DateTimeKind.Local).AddTicks(6472),
                            ReplyText = "Eligendi enim aut dolor sed quidem ipsa facilis."
                        },
                        new
                        {
                            ID = new Guid("55a36926-529a-421b-b768-3d4aca2d0787"),
                            ReplyCommentId = new Guid("6e9318f8-1fe8-45ab-b519-ccbb23c73818"),
                            ReplyPostDate = new DateTime(2022, 9, 18, 18, 12, 41, 931, DateTimeKind.Local).AddTicks(4174),
                            ReplyText = "Sint hic aut. Temporibus ratione sunt expedita tempore praesentium. Sit culpa numquam. Enim et fuga. Praesentium rerum amet quas eveniet doloribus optio odit. Enim dolorem libero voluptas quidem."
                        },
                        new
                        {
                            ID = new Guid("aab7a3e4-aea5-423c-99e6-1f09ed63d47b"),
                            ReplyCommentId = new Guid("31a55e74-e566-4302-92e4-77b34240637e"),
                            ReplyPostDate = new DateTime(2022, 9, 17, 17, 42, 7, 799, DateTimeKind.Local).AddTicks(7816),
                            ReplyText = "Impedit et odit reprehenderit possimus doloremque aperiam cum. Ut assumenda tempora cumque ducimus quidem officia sed veritatis rerum. Repellendus quis quam aut sequi a enim corrupti. Et nihil ea aperiam. Quibusdam dolor officia deserunt."
                        },
                        new
                        {
                            ID = new Guid("d49646bd-9505-4b5e-a290-0419b32152ab"),
                            ReplyCommentId = new Guid("034dcfe2-f065-4e26-b0d3-8ef3dc29ba50"),
                            ReplyPostDate = new DateTime(2022, 9, 13, 6, 28, 20, 355, DateTimeKind.Local).AddTicks(3823),
                            ReplyText = "sequi"
                        },
                        new
                        {
                            ID = new Guid("0bb39075-d196-4df8-8010-a6ca8526a580"),
                            ReplyCommentId = new Guid("cd368a36-f4da-4b1b-9ce7-2fc2ace6dcc0"),
                            ReplyPostDate = new DateTime(2022, 12, 12, 20, 17, 38, 254, DateTimeKind.Local).AddTicks(4485),
                            ReplyText = "Dignissimos dolores aliquam."
                        },
                        new
                        {
                            ID = new Guid("617e6071-6ea1-4461-941d-0670ae4e584c"),
                            ReplyCommentId = new Guid("6c927d62-9b0b-4e94-b0ea-ea2f6f2178c8"),
                            ReplyPostDate = new DateTime(2022, 10, 30, 13, 41, 49, 89, DateTimeKind.Local).AddTicks(6560),
                            ReplyText = "Maxime vero vero cupiditate libero adipisci laudantium occaecati.\nDolorum incidunt est delectus aut.\nConsectetur modi aut ea dicta quo cupiditate molestiae delectus magni.\nInventore voluptate aperiam doloremque dolorum voluptatem quia sint sed hic.\nUt distinctio totam ipsam quasi."
                        },
                        new
                        {
                            ID = new Guid("45f4a3d9-11f6-4b65-9559-934da54f8a34"),
                            ReplyCommentId = new Guid("ca01b1cf-a0dc-4611-b6bc-77c51afbb255"),
                            ReplyPostDate = new DateTime(2022, 12, 22, 10, 37, 56, 88, DateTimeKind.Local).AddTicks(1771),
                            ReplyText = "autem"
                        },
                        new
                        {
                            ID = new Guid("90dc8deb-0c0e-4ffa-a847-fe024ee2e900"),
                            ReplyCommentId = new Guid("589cbd4c-ce46-4139-bd08-72bdb764de9c"),
                            ReplyPostDate = new DateTime(2023, 5, 11, 17, 36, 7, 533, DateTimeKind.Local).AddTicks(6456),
                            ReplyText = "Quod voluptate eius nesciunt minima perspiciatis harum dicta facere non.\nIpsum ut doloremque ea quia natus eos.\nAsperiores blanditiis eum a."
                        },
                        new
                        {
                            ID = new Guid("ebdc377c-8478-4e2e-90af-3a5edbeefffe"),
                            ReplyCommentId = new Guid("81923ef3-6adb-4d51-aace-d671a0382227"),
                            ReplyPostDate = new DateTime(2023, 4, 14, 13, 50, 42, 163, DateTimeKind.Local).AddTicks(1988),
                            ReplyText = "Quia ut facilis velit quis sunt dolorum non."
                        },
                        new
                        {
                            ID = new Guid("758ffdff-077a-4778-8227-9c4bff8f4f6c"),
                            ReplyCommentId = new Guid("5610e6ef-282c-4be1-828c-57b0b5202d33"),
                            ReplyPostDate = new DateTime(2023, 4, 17, 5, 10, 21, 45, DateTimeKind.Local).AddTicks(6001),
                            ReplyText = "Eveniet rerum ut odit esse et eius id placeat.\nTempore quas necessitatibus doloremque.\nAsperiores nostrum esse debitis veniam quis sapiente facere.\nRerum deleniti culpa temporibus modi facere sed corporis ullam.\nEa tenetur corrupti.\nAb eaque et quia voluptatem et aliquid."
                        },
                        new
                        {
                            ID = new Guid("4181608b-d6ee-47cd-81c6-bed5f419e0d8"),
                            ReplyCommentId = new Guid("4c4e7eef-ea3e-41ac-bf5a-255a89d7a632"),
                            ReplyPostDate = new DateTime(2022, 11, 3, 8, 12, 52, 931, DateTimeKind.Local).AddTicks(7116),
                            ReplyText = "Vero deleniti qui ea quis fugit dolorem et unde qui."
                        },
                        new
                        {
                            ID = new Guid("01090724-404f-463a-a156-bdafce2d4f8e"),
                            ReplyCommentId = new Guid("924cc7ef-791b-4abe-8665-c914c6de51ba"),
                            ReplyPostDate = new DateTime(2022, 9, 15, 5, 39, 2, 587, DateTimeKind.Local).AddTicks(7418),
                            ReplyText = "tenetur"
                        },
                        new
                        {
                            ID = new Guid("b37556b1-180a-4dff-8b5e-ddd811ed425e"),
                            ReplyCommentId = new Guid("516eab17-30f1-401d-af6e-8992f666354e"),
                            ReplyPostDate = new DateTime(2022, 10, 19, 17, 6, 13, 619, DateTimeKind.Local).AddTicks(6114),
                            ReplyText = "Delectus distinctio sed numquam quia et voluptatem rem.\nOmnis blanditiis excepturi atque et placeat ipsa velit et et."
                        },
                        new
                        {
                            ID = new Guid("d6cb5132-5469-499c-9059-d160aa240f3b"),
                            ReplyCommentId = new Guid("4ae7e910-ed61-4852-a80c-e7cd955c5f89"),
                            ReplyPostDate = new DateTime(2022, 10, 20, 1, 20, 46, 406, DateTimeKind.Local).AddTicks(8768),
                            ReplyText = "Repellat nisi et illum beatae recusandae velit."
                        },
                        new
                        {
                            ID = new Guid("7d8c89f8-fb1b-426a-ac1f-365e32bb2fdc"),
                            ReplyCommentId = new Guid("18611973-ae6e-43e8-bf4d-4a094c88f1ba"),
                            ReplyPostDate = new DateTime(2023, 2, 21, 6, 3, 50, 468, DateTimeKind.Local).AddTicks(7157),
                            ReplyText = "Aut deserunt numquam."
                        },
                        new
                        {
                            ID = new Guid("58a425ce-4809-426e-9cab-11e47d3e26df"),
                            ReplyCommentId = new Guid("ca52595c-706d-4596-816a-e3c5e6d21543"),
                            ReplyPostDate = new DateTime(2023, 2, 9, 4, 49, 1, 575, DateTimeKind.Local).AddTicks(9074),
                            ReplyText = "Necessitatibus explicabo ut iusto iste ea. Rerum tempora corrupti rerum tempora voluptas aut. Et sint et est. Numquam dolor qui debitis quae. Qui dignissimos ipsam necessitatibus neque. Maxime praesentium nostrum sint corporis repudiandae cumque commodi totam."
                        },
                        new
                        {
                            ID = new Guid("ac9e8706-5fa8-4d48-99b7-5e8e89d24bcd"),
                            ReplyCommentId = new Guid("7b632433-ca6d-421d-b3ab-e1daeb6ca005"),
                            ReplyPostDate = new DateTime(2023, 1, 28, 19, 16, 12, 424, DateTimeKind.Local).AddTicks(9950),
                            ReplyText = "rerum"
                        },
                        new
                        {
                            ID = new Guid("221dae9d-05b2-4b0f-91a4-a6c40d6617e7"),
                            ReplyCommentId = new Guid("48c954de-ae23-4759-98fb-0c124bfadc87"),
                            ReplyPostDate = new DateTime(2022, 12, 7, 4, 14, 43, 315, DateTimeKind.Local).AddTicks(7374),
                            ReplyText = "Omnis cupiditate eos sed omnis modi odio et.\nPossimus facilis fugiat dignissimos ea ad nesciunt quia veniam aut.\nUllam temporibus dolorem quam consequatur quasi doloribus.\nExplicabo doloribus ut iste esse.\nAsperiores vel consequuntur fugiat adipisci minima voluptatem libero est eius."
                        },
                        new
                        {
                            ID = new Guid("5ae55e5b-bdb2-4a60-98cb-74a59146a407"),
                            ReplyCommentId = new Guid("1323d20a-3bfe-4088-9296-2a20e8028bbc"),
                            ReplyPostDate = new DateTime(2022, 7, 11, 18, 17, 52, 375, DateTimeKind.Local).AddTicks(2549),
                            ReplyText = "Explicabo ea consequuntur. Ex deserunt molestiae suscipit quisquam occaecati. Fugiat iusto sunt maiores. Cumque est cumque minima culpa debitis nobis a id porro. Sequi consequatur explicabo sequi perferendis qui vel. Vel aut officiis vel sed."
                        },
                        new
                        {
                            ID = new Guid("a699856f-f589-4e7f-aaa6-b3f819208aa9"),
                            ReplyCommentId = new Guid("18d81b75-378c-4daa-ba68-e3ce723ae502"),
                            ReplyPostDate = new DateTime(2022, 5, 28, 6, 3, 32, 592, DateTimeKind.Local).AddTicks(8629),
                            ReplyText = "qui"
                        },
                        new
                        {
                            ID = new Guid("ef58d3f3-df44-477c-b19b-a5736650985a"),
                            ReplyCommentId = new Guid("8c12089f-173f-4012-993b-1088798c4990"),
                            ReplyPostDate = new DateTime(2022, 12, 14, 3, 31, 1, 283, DateTimeKind.Local).AddTicks(2685),
                            ReplyText = "Consequatur quisquam facere id reiciendis explicabo nesciunt iure. Architecto quo qui in. Vero quasi ut expedita odio eos recusandae sit nihil. Optio qui qui. Soluta dolor debitis reiciendis aut iure ut sint. Quia rerum minus temporibus."
                        },
                        new
                        {
                            ID = new Guid("c92fe676-2e4d-45a3-abcc-dca8c10d7624"),
                            ReplyCommentId = new Guid("47cdaa48-c1b6-46b2-a7f2-4781d581da0f"),
                            ReplyPostDate = new DateTime(2022, 10, 1, 7, 39, 24, 469, DateTimeKind.Local).AddTicks(3155),
                            ReplyText = "Aut fugit cupiditate eveniet atque.\nNumquam cupiditate cum rerum illum esse."
                        },
                        new
                        {
                            ID = new Guid("e8140296-28dd-44d4-b6b7-d7af1f0aa7ed"),
                            ReplyCommentId = new Guid("a29535b5-405e-4d16-b70f-89a270c242c0"),
                            ReplyPostDate = new DateTime(2022, 7, 22, 23, 46, 5, 311, DateTimeKind.Local).AddTicks(2546),
                            ReplyText = "Corrupti minus et corporis fuga laudantium praesentium amet distinctio excepturi. Consequatur et architecto assumenda. Inventore vel voluptatem autem nemo repellat."
                        },
                        new
                        {
                            ID = new Guid("a9f9a1a6-2bb2-4394-b81e-f77f80b4eb29"),
                            ReplyCommentId = new Guid("47f55c4b-65bc-43cd-a450-10202006338d"),
                            ReplyPostDate = new DateTime(2023, 5, 20, 5, 1, 58, 174, DateTimeKind.Local).AddTicks(1254),
                            ReplyText = "iure"
                        },
                        new
                        {
                            ID = new Guid("7bd20b07-a4d4-425f-b613-c897fdefcfd9"),
                            ReplyCommentId = new Guid("df7fb061-24db-474f-9748-6eda40e83412"),
                            ReplyPostDate = new DateTime(2023, 4, 14, 15, 24, 20, 647, DateTimeKind.Local).AddTicks(4621),
                            ReplyText = "Et non et ut ut. Sint iure dolorum in molestiae nihil odio quo nemo. Beatae vel fugiat qui voluptatum fuga. Rerum rerum consequatur. Officia praesentium ut architecto amet explicabo quis."
                        },
                        new
                        {
                            ID = new Guid("cd554fab-1ef0-49f0-a7ed-bfbfab27e953"),
                            ReplyCommentId = new Guid("d0ef0f9c-bedf-422f-867e-e412fadb26ea"),
                            ReplyPostDate = new DateTime(2023, 5, 22, 7, 46, 54, 5, DateTimeKind.Local).AddTicks(3227),
                            ReplyText = "Voluptas quidem consequuntur dolore ut ea animi. Quia rerum quod tempora ea culpa magni quia necessitatibus a. Porro incidunt atque qui. Veniam et cumque accusantium sint qui ducimus rerum eos ipsa."
                        },
                        new
                        {
                            ID = new Guid("b2e51c9e-a7a6-40c0-a896-b0c6c6376f7c"),
                            ReplyCommentId = new Guid("78e5172e-edcf-4a33-a68e-3c882e3ace28"),
                            ReplyPostDate = new DateTime(2022, 10, 25, 12, 41, 17, 402, DateTimeKind.Local).AddTicks(2452),
                            ReplyText = "culpa"
                        },
                        new
                        {
                            ID = new Guid("ed2ae412-ba5a-4f76-9188-ef2bcac9a949"),
                            ReplyCommentId = new Guid("51165c35-e1eb-41c9-965a-045c4bf6dec3"),
                            ReplyPostDate = new DateTime(2022, 7, 3, 20, 31, 6, 793, DateTimeKind.Local).AddTicks(462),
                            ReplyText = "Velit ullam commodi voluptas."
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.HasOne("Comments.Data.Models.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("CommentFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.HasOne("Comments.Data.Models.Comment", "Comment")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
