// <auto-generated />
using System;
using Comments.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Migrations.Migrations
{
    [DbContext(typeof(CommentsContext))]
    [Migration("20230523192208_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Comments", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("2c2cab88-11dc-48d5-8466-15a5e0d3e9fb"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 23, 11, 59, 36, 866, DateTimeKind.Local).AddTicks(9985),
                            Text = "quos",
                            Theme = "a"
                        },
                        new
                        {
                            ID = new Guid("928d8324-c8c2-4aed-8aaa-59438e0d1142"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 4, 7, 14, 8, 36, 219, DateTimeKind.Local).AddTicks(5770),
                            Text = "Explicabo ut omnis.\nQuam nobis et.\nEt in aut perferendis maxime repudiandae nisi minima laudantium rerum.\nDolor rerum aut sunt est quae hic.\nQuibusdam soluta in dolorem rerum rem debitis aut dolor.",
                            Theme = "debitis"
                        },
                        new
                        {
                            ID = new Guid("19fa9004-64bf-4cd6-bde2-a9efd845a6e1"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 12, 4, 12, 0, 48, 297, DateTimeKind.Local).AddTicks(7419),
                            Text = "Nesciunt et hic consequatur atque nostrum occaecati.",
                            Theme = "officia"
                        },
                        new
                        {
                            ID = new Guid("499da793-7e00-4d78-9fba-5406cb1c090c"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 27, 16, 35, 19, 421, DateTimeKind.Local).AddTicks(8194),
                            Text = "Qui suscipit quo quaerat dignissimos non ut. Nobis consequatur et. Repudiandae qui id consequatur qui. Error debitis suscipit omnis sint eum.",
                            Theme = "temporibus"
                        },
                        new
                        {
                            ID = new Guid("04d21d33-a0da-4a7e-a936-488705db16db"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 7, 3, 6, 50, 53, 881, DateTimeKind.Local).AddTicks(8158),
                            Text = "repellat",
                            Theme = "suscipit"
                        },
                        new
                        {
                            ID = new Guid("449d3eaa-9eb1-43ec-b304-811a6dff8c1e"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 7, 11, 9, 1, 3, 753, DateTimeKind.Local).AddTicks(8559),
                            Text = "Necessitatibus quia totam.\nEligendi inventore et blanditiis commodi ut consequatur.\nQuo sed voluptate corrupti omnis omnis beatae.\nHic ea accusamus iure consequatur quia qui cumque in minus.",
                            Theme = "saepe"
                        },
                        new
                        {
                            ID = new Guid("d3fd6617-125a-46a1-aefc-34e8a77e1fce"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 2, 20, 10, 54, 25, 726, DateTimeKind.Local).AddTicks(8978),
                            Text = "At voluptates et nisi iste velit qui. Eos voluptas reprehenderit eos ea veritatis aliquam possimus quaerat consequuntur. Quidem quo hic consequatur autem. Corrupti amet itaque iusto nostrum dolor illum. Et totam in eius.",
                            Theme = "fugiat"
                        },
                        new
                        {
                            ID = new Guid("27163ef6-b75f-423c-94e5-cfb93c45c989"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 3, 6, 0, 42, 39, 399, DateTimeKind.Local).AddTicks(1377),
                            Text = "Consequuntur sunt reprehenderit mollitia omnis aut tenetur provident et harum.\nIncidunt placeat aut et rerum quis est eaque.\nReprehenderit fugit aliquam sed explicabo.\nAb est rerum aut ratione non rerum quia et neque.\nPlaceat et voluptate sit inventore culpa.\nVoluptatibus quo perferendis eum neque est excepturi quisquam.",
                            Theme = "voluptatem"
                        },
                        new
                        {
                            ID = new Guid("47e257d7-ed53-40e5-99b4-c20d04d91eb2"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 10, 28, 9, 24, 16, 219, DateTimeKind.Local).AddTicks(4518),
                            Text = "A voluptas ullam sequi vero adipisci libero mollitia voluptas.\nTotam facere voluptatem laudantium asperiores consequatur vitae.\nEos illo eum perferendis quod saepe.",
                            Theme = "recusandae"
                        },
                        new
                        {
                            ID = new Guid("1ef9b8ca-baca-40f6-b6e4-8a9583800475"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 19, 5, 8, 3, 387, DateTimeKind.Local).AddTicks(2111),
                            Text = "Sit voluptatem eligendi iusto eveniet.",
                            Theme = "a"
                        },
                        new
                        {
                            ID = new Guid("30371de7-0c5e-436d-a4ae-49d344269ab6"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 13, 0, 36, 3, 389, DateTimeKind.Local).AddTicks(3595),
                            Text = "Debitis enim nostrum optio voluptatem qui eius.",
                            Theme = "dolorum"
                        },
                        new
                        {
                            ID = new Guid("771f9110-ddbb-4473-b242-9592f8454161"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 3, 10, 16, 41, 57, 790, DateTimeKind.Local).AddTicks(806),
                            Text = "Nobis ipsa nihil aut quibusdam sit.",
                            Theme = "fuga"
                        },
                        new
                        {
                            ID = new Guid("2db37b25-03b6-48c2-a39f-439bd6d3daf3"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 1, 19, 9, 24, 21, 474, DateTimeKind.Local).AddTicks(285),
                            Text = "Ipsum distinctio maxime commodi enim.\nQuibusdam modi itaque omnis quos.\nFugiat et cupiditate ut doloribus dolor odio.\nQuia quaerat odit tempore alias ab occaecati magni blanditiis.\nQuia minus dolorem cum perferendis neque non qui expedita.",
                            Theme = "vel"
                        },
                        new
                        {
                            ID = new Guid("b4d17469-4bb3-4ad5-b77b-0405339dcd20"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 11, 2, 11, 42, 3, 680, DateTimeKind.Local).AddTicks(2969),
                            Text = "Nobis explicabo facere aut laboriosam ut quia velit. Quam non recusandae. Enim qui aut aut vel ut omnis eaque ratione voluptas. Eum cupiditate quis. Ratione iure consequatur.",
                            Theme = "saepe"
                        },
                        new
                        {
                            ID = new Guid("95f00057-2785-4a06-a8cd-4928b57d7727"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 19, 6, 30, 26, 394, DateTimeKind.Local).AddTicks(7546),
                            Text = "Enim ut error occaecati sed cum exercitationem modi ex et. Dolores commodi libero est. Corporis nemo eligendi. Vel veniam tenetur reprehenderit et commodi perspiciatis mollitia. Eos ut possimus cum aut libero.",
                            Theme = "a"
                        },
                        new
                        {
                            ID = new Guid("c6c0ebbc-e61a-479a-ba27-babc4b679634"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 7, 7, 7, 58, 55, 734, DateTimeKind.Local).AddTicks(6603),
                            Text = "necessitatibus",
                            Theme = "est"
                        },
                        new
                        {
                            ID = new Guid("b46f35e8-162b-4dd5-ad9d-9645d3a5af0b"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 12, 12, 18, 46, 6, 628, DateTimeKind.Local).AddTicks(8354),
                            Text = "sit",
                            Theme = "voluptatem"
                        },
                        new
                        {
                            ID = new Guid("a972e1a0-6776-4f40-9973-8f91b0e66b8c"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 8, 10, 17, 57, 5, 735, DateTimeKind.Local).AddTicks(442),
                            Text = "Est voluptatem nisi sequi perspiciatis.",
                            Theme = "accusantium"
                        },
                        new
                        {
                            ID = new Guid("986cca32-6160-4570-981d-5648e896e4ee"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 6, 14, 14, 46, 29, 562, DateTimeKind.Local).AddTicks(6459),
                            Text = "itaque",
                            Theme = "dicta"
                        },
                        new
                        {
                            ID = new Guid("8722eb57-e451-48d1-8b82-5ff767d58e17"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 1, 29, 2, 48, 4, 190, DateTimeKind.Local).AddTicks(1552),
                            Text = "Ut hic fugiat.\nQui aut hic numquam asperiores temporibus.\nAut libero praesentium voluptatem voluptatem.\nEst et maiores.",
                            Theme = "excepturi"
                        },
                        new
                        {
                            ID = new Guid("3892b4e2-369f-4184-8a88-81706960d694"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 20, 9, 58, 40, 620, DateTimeKind.Local).AddTicks(5004),
                            Text = "Et asperiores ipsam perferendis natus totam. Est nostrum exercitationem. Voluptatem nostrum nulla officiis doloribus velit sunt nemo consequatur. Animi autem ipsa sit itaque eveniet. Non sed ex numquam sit doloribus consequatur.",
                            Theme = "eligendi"
                        },
                        new
                        {
                            ID = new Guid("6d20f885-a18e-47c6-8d01-6d5241e009c1"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 8, 11, 19, 48, 19, 332, DateTimeKind.Local).AddTicks(8631),
                            Text = "Dolorum voluptatum voluptas alias.",
                            Theme = "esse"
                        },
                        new
                        {
                            ID = new Guid("409e9bbf-e29c-4395-9aa4-c0d2da2bbb8d"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 7, 14, 13, 2, 45, 590, DateTimeKind.Local).AddTicks(5340),
                            Text = "Natus omnis culpa ut sequi et reiciendis aperiam quia.",
                            Theme = "laboriosam"
                        },
                        new
                        {
                            ID = new Guid("dd62c50c-609d-4152-8a4a-c0edf26dbb82"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 5, 16, 11, 26, 4, 739, DateTimeKind.Local).AddTicks(42),
                            Text = "Quia fugit consectetur nulla. Velit provident sapiente consequatur libero et molestias voluptate. Quae aut maxime vel alias repudiandae molestias. Omnis et provident expedita sed non illum fugiat.",
                            Theme = "praesentium"
                        },
                        new
                        {
                            ID = new Guid("34ee4e3a-45d4-455a-b069-7c39a312ab08"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 6, 28, 20, 22, 16, 923, DateTimeKind.Local).AddTicks(8344),
                            Text = "voluptas",
                            Theme = "molestias"
                        },
                        new
                        {
                            ID = new Guid("bb2400dc-75f5-438a-8c52-a81869b1d233"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 9, 13, 13, 1, 31, 618, DateTimeKind.Local).AddTicks(4848),
                            Text = "minima",
                            Theme = "exercitationem"
                        },
                        new
                        {
                            ID = new Guid("145331a8-af26-4009-a991-1113eb656a54"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 8, 17, 8, 58, 15, 387, DateTimeKind.Local).AddTicks(3655),
                            Text = "Exercitationem nostrum accusantium dolor ducimus.\nVel sit et illo dolore aut iste tempora qui.\nEveniet ea animi eligendi voluptatem sint suscipit cum quaerat.\nAd sed velit eum.\nNobis iure nihil sit.\nMinima deleniti aut ut illum est tempore dolor voluptatem sed.",
                            Theme = "fugiat"
                        },
                        new
                        {
                            ID = new Guid("e916bfb2-3621-42e2-a476-13f3d9d229af"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2023, 1, 8, 4, 33, 49, 953, DateTimeKind.Local).AddTicks(2601),
                            Text = "Vitae esse et doloribus.\nConsequatur quis est voluptatem in molestiae id neque rerum.\nDolorem aspernatur placeat sunt molestias rem quo voluptas dolorum quis.",
                            Theme = "est"
                        },
                        new
                        {
                            ID = new Guid("1d24d398-ec78-41e2-be23-2c3de86ca8d1"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 8, 15, 10, 27, 43, 236, DateTimeKind.Local).AddTicks(742),
                            Text = "sint",
                            Theme = "ea"
                        },
                        new
                        {
                            ID = new Guid("74d3b621-020f-4ee3-976d-2118f3b777bb"),
                            FeedbackId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PostDate = new DateTime(2022, 8, 20, 3, 13, 58, 16, DateTimeKind.Local).AddTicks(6105),
                            Text = "Accusantium mollitia rerum ut odio totam molestias eligendi quisquam modi. Dolores velit optio dicta rerum aliquid. Alias sed perferendis eos omnis.",
                            Theme = "atque"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeedbackTheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.ToTable("Feedbacks", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b3f7a682-8194-43d5-95e5-449c9f00b5b9"),
                            CommentId = new Guid("2c2cab88-11dc-48d5-8466-15a5e0d3e9fb"),
                            FeedbackTheme = "Suggestion"
                        },
                        new
                        {
                            ID = new Guid("f013d319-b12c-41fe-8555-3db4c4bbba77"),
                            CommentId = new Guid("928d8324-c8c2-4aed-8aaa-59438e0d1142"),
                            FeedbackTheme = "Suggestion"
                        },
                        new
                        {
                            ID = new Guid("a211ca06-0a44-4412-8368-541b72ba941d"),
                            CommentId = new Guid("19fa9004-64bf-4cd6-bde2-a9efd845a6e1"),
                            FeedbackTheme = "Suggestion"
                        },
                        new
                        {
                            ID = new Guid("76a1a4c4-f1c1-4989-abca-ffcfe6e27aaa"),
                            CommentId = new Guid("499da793-7e00-4d78-9fba-5406cb1c090c"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("7d40098c-7b37-4288-ab5d-af52c41b92b5"),
                            CommentId = new Guid("04d21d33-a0da-4a7e-a936-488705db16db"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("29ec375c-ff11-41c8-98f9-0a364a4712f0"),
                            CommentId = new Guid("449d3eaa-9eb1-43ec-b304-811a6dff8c1e"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("e455b905-270f-4cfa-944b-34e9752ec1da"),
                            CommentId = new Guid("d3fd6617-125a-46a1-aefc-34e8a77e1fce"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("99f5ed78-7462-46f8-b05b-d1f6517bf00e"),
                            CommentId = new Guid("27163ef6-b75f-423c-94e5-cfb93c45c989"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("072be93a-bc67-4210-a52a-9e3cf1782a32"),
                            CommentId = new Guid("47e257d7-ed53-40e5-99b4-c20d04d91eb2"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("dfaf91fe-2b85-4cdc-a75c-8762b28f9911"),
                            CommentId = new Guid("1ef9b8ca-baca-40f6-b6e4-8a9583800475"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("a4a56f2d-0135-47a9-a66b-2fd260f903bc"),
                            CommentId = new Guid("30371de7-0c5e-436d-a4ae-49d344269ab6"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("6b3596cf-078f-4ee5-9096-3ceb67a0b056"),
                            CommentId = new Guid("771f9110-ddbb-4473-b242-9592f8454161"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("ed9e2e99-be69-409a-ae73-aed04277de8c"),
                            CommentId = new Guid("2db37b25-03b6-48c2-a39f-439bd6d3daf3"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("d2794bf9-7f50-4b59-b728-27b476720bf9"),
                            CommentId = new Guid("b4d17469-4bb3-4ad5-b77b-0405339dcd20"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("1a5e229c-64bc-48a4-803f-9e38bab07456"),
                            CommentId = new Guid("95f00057-2785-4a06-a8cd-4928b57d7727"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("a5ed943e-8ad6-4db5-9d67-ea130196a39f"),
                            CommentId = new Guid("c6c0ebbc-e61a-479a-ba27-babc4b679634"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("f619fc19-91a6-4eb7-a23d-dcdb0d479c10"),
                            CommentId = new Guid("b46f35e8-162b-4dd5-ad9d-9645d3a5af0b"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("4e6cfb0a-f81a-4de9-9ab9-f829e19e2646"),
                            CommentId = new Guid("a972e1a0-6776-4f40-9973-8f91b0e66b8c"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("384fc0c4-a778-4f04-a96e-5703c7990588"),
                            CommentId = new Guid("986cca32-6160-4570-981d-5648e896e4ee"),
                            FeedbackTheme = "Suggestion"
                        },
                        new
                        {
                            ID = new Guid("e5ad2c9f-5b94-4895-82c1-6fa24b2309c1"),
                            CommentId = new Guid("8722eb57-e451-48d1-8b82-5ff767d58e17"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("939eac44-e210-4d1a-968e-0d1503507d9a"),
                            CommentId = new Guid("3892b4e2-369f-4184-8a88-81706960d694"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("09745ada-16b8-4eaa-8521-bf7c4f4cf013"),
                            CommentId = new Guid("6d20f885-a18e-47c6-8d01-6d5241e009c1"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("6611ce07-71be-43bd-9480-3a332301f5b3"),
                            CommentId = new Guid("409e9bbf-e29c-4395-9aa4-c0d2da2bbb8d"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("bbd3c3a4-984d-4603-a5b7-ea92654c8d51"),
                            CommentId = new Guid("dd62c50c-609d-4152-8a4a-c0edf26dbb82"),
                            FeedbackTheme = "Comment"
                        },
                        new
                        {
                            ID = new Guid("aa24a61d-081d-4680-a255-8af876c98b40"),
                            CommentId = new Guid("34ee4e3a-45d4-455a-b069-7c39a312ab08"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("09d88014-1ed8-4643-b894-669adbd82672"),
                            CommentId = new Guid("bb2400dc-75f5-438a-8c52-a81869b1d233"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("2af6cf83-fb34-4b37-8ab6-8e257ed69485"),
                            CommentId = new Guid("145331a8-af26-4009-a991-1113eb656a54"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("3028df73-73ef-4fed-a1fc-3bdb55120388"),
                            CommentId = new Guid("e916bfb2-3621-42e2-a476-13f3d9d229af"),
                            FeedbackTheme = "Issue"
                        },
                        new
                        {
                            ID = new Guid("32352100-8758-4118-898d-e7b7e5ad9864"),
                            CommentId = new Guid("1d24d398-ec78-41e2-be23-2c3de86ca8d1"),
                            FeedbackTheme = "LoveIt"
                        },
                        new
                        {
                            ID = new Guid("8fe024e6-ec36-41df-8b79-405748c93971"),
                            CommentId = new Guid("74d3b621-020f-4ee3-976d-2118f3b777bb"),
                            FeedbackTheme = "Issue"
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.HasIndex("CommentId");

                    b.ToTable("Replies", "Comments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("3caef44d-293c-40fe-9fbc-4d16f50fa00a"),
                            CommentId = new Guid("2c2cab88-11dc-48d5-8466-15a5e0d3e9fb"),
                            PostDate = new DateTime(2022, 8, 15, 5, 6, 44, 9, DateTimeKind.Local).AddTicks(1921),
                            Text = "Dignissimos necessitatibus blanditiis quia quis enim voluptas consequatur eius. Enim fugiat facilis ad mollitia quod sunt error ratione deserunt. Quo nemo maxime iste occaecati placeat mollitia sed velit. Dolores velit non est provident inventore provident voluptas et iusto."
                        },
                        new
                        {
                            ID = new Guid("6a297b48-3d36-420a-82b6-d9090a507d86"),
                            CommentId = new Guid("928d8324-c8c2-4aed-8aaa-59438e0d1142"),
                            PostDate = new DateTime(2023, 4, 21, 0, 27, 34, 849, DateTimeKind.Local).AddTicks(2053),
                            Text = "Voluptas corporis sequi. Sit perferendis enim quia. Iste minus consequatur illo cum. Ipsa deserunt nihil maiores."
                        },
                        new
                        {
                            ID = new Guid("bac61919-a109-413a-b1fc-d174ecf45d89"),
                            CommentId = new Guid("19fa9004-64bf-4cd6-bde2-a9efd845a6e1"),
                            PostDate = new DateTime(2022, 10, 10, 7, 9, 2, 971, DateTimeKind.Local).AddTicks(9412),
                            Text = "Quam asperiores sit neque quo voluptatem."
                        },
                        new
                        {
                            ID = new Guid("a7b3ac3a-995d-40a5-ba58-bc77d08a90c8"),
                            CommentId = new Guid("499da793-7e00-4d78-9fba-5406cb1c090c"),
                            PostDate = new DateTime(2022, 7, 6, 15, 25, 40, 368, DateTimeKind.Local).AddTicks(5071),
                            Text = "Tempore saepe minima saepe ad eum. Voluptatem occaecati hic nulla. Est vel eveniet deserunt est inventore odit quo laudantium. Quasi molestiae recusandae consequuntur soluta."
                        },
                        new
                        {
                            ID = new Guid("bb7419a4-131c-4f40-90c1-0cbf900487f6"),
                            CommentId = new Guid("04d21d33-a0da-4a7e-a936-488705db16db"),
                            PostDate = new DateTime(2023, 1, 25, 10, 44, 37, 75, DateTimeKind.Local).AddTicks(1613),
                            Text = "Labore pariatur fugiat maxime sint non natus."
                        },
                        new
                        {
                            ID = new Guid("e59eee9e-7d19-4ad7-b73d-53696a2fa372"),
                            CommentId = new Guid("449d3eaa-9eb1-43ec-b304-811a6dff8c1e"),
                            PostDate = new DateTime(2022, 7, 27, 7, 19, 18, 416, DateTimeKind.Local).AddTicks(2530),
                            Text = "Perferendis sit delectus alias aliquid quas exercitationem consequatur eius eum."
                        },
                        new
                        {
                            ID = new Guid("647f4399-92fb-4d78-a45b-cb849c58fa06"),
                            CommentId = new Guid("d3fd6617-125a-46a1-aefc-34e8a77e1fce"),
                            PostDate = new DateTime(2022, 9, 14, 19, 28, 20, 822, DateTimeKind.Local).AddTicks(3779),
                            Text = "Quisquam et non dicta et sequi consectetur. Rerum ullam dicta possimus rerum animi laborum sint qui. Ab ut ut dolore. Molestiae cumque ad."
                        },
                        new
                        {
                            ID = new Guid("129c41ec-09a0-482a-8cf8-64542f516334"),
                            CommentId = new Guid("27163ef6-b75f-423c-94e5-cfb93c45c989"),
                            PostDate = new DateTime(2023, 4, 7, 9, 33, 1, 950, DateTimeKind.Local).AddTicks(3251),
                            Text = "nobis"
                        },
                        new
                        {
                            ID = new Guid("ce09a873-71a9-481a-b1fc-edfc64642620"),
                            CommentId = new Guid("47e257d7-ed53-40e5-99b4-c20d04d91eb2"),
                            PostDate = new DateTime(2023, 5, 7, 1, 15, 16, 161, DateTimeKind.Local).AddTicks(8230),
                            Text = "iure"
                        },
                        new
                        {
                            ID = new Guid("38269ae7-d595-4a47-999a-846863990940"),
                            CommentId = new Guid("1ef9b8ca-baca-40f6-b6e4-8a9583800475"),
                            PostDate = new DateTime(2023, 3, 2, 22, 6, 22, 89, DateTimeKind.Local).AddTicks(7758),
                            Text = "tempora"
                        },
                        new
                        {
                            ID = new Guid("d947ca00-6e70-4228-8f29-dee86993160b"),
                            CommentId = new Guid("30371de7-0c5e-436d-a4ae-49d344269ab6"),
                            PostDate = new DateTime(2022, 10, 1, 4, 34, 58, 510, DateTimeKind.Local).AddTicks(770),
                            Text = "vitae"
                        },
                        new
                        {
                            ID = new Guid("0c6bb331-7938-46c3-b956-e943d809fede"),
                            CommentId = new Guid("771f9110-ddbb-4473-b242-9592f8454161"),
                            PostDate = new DateTime(2023, 1, 13, 2, 58, 18, 649, DateTimeKind.Local).AddTicks(3744),
                            Text = "Consequatur corporis exercitationem qui molestiae.\nQuisquam sint ab dolorum excepturi ut reiciendis.\nOptio dolor blanditiis debitis totam eos sed sed.\nPraesentium voluptate dolorum.\nAlias et in.\nTempora dolor exercitationem consequuntur sunt rem et deleniti."
                        },
                        new
                        {
                            ID = new Guid("6337dfee-f4bb-4244-bd99-8a0176ebce4e"),
                            CommentId = new Guid("2db37b25-03b6-48c2-a39f-439bd6d3daf3"),
                            PostDate = new DateTime(2023, 3, 18, 9, 46, 50, 146, DateTimeKind.Local).AddTicks(4984),
                            Text = "Omnis aliquam suscipit. Doloremque necessitatibus aut quibusdam. Rerum dolores minima ea quisquam vero ut. Fuga nulla consectetur voluptas. Nostrum quis nihil ex."
                        },
                        new
                        {
                            ID = new Guid("d1b51eac-f33d-4180-a49a-62fd499e68db"),
                            CommentId = new Guid("b4d17469-4bb3-4ad5-b77b-0405339dcd20"),
                            PostDate = new DateTime(2023, 1, 31, 0, 45, 30, 78, DateTimeKind.Local).AddTicks(5298),
                            Text = "Sit voluptas deleniti. Enim velit modi provident consequatur culpa error fuga voluptatibus magni. Numquam qui ut."
                        },
                        new
                        {
                            ID = new Guid("51eaebbd-0f54-4a7f-8d29-d002e95f6552"),
                            CommentId = new Guid("95f00057-2785-4a06-a8cd-4928b57d7727"),
                            PostDate = new DateTime(2023, 1, 1, 22, 24, 55, 674, DateTimeKind.Local).AddTicks(8173),
                            Text = "Eum quo ea.\nOfficia totam quia ut aperiam voluptas vero sapiente rerum eum.\nFacilis rerum fugiat aperiam provident asperiores modi optio nesciunt recusandae.\nSunt cum sit labore quo qui eum ut in neque.\nEnim illum molestiae ratione facere aliquid quae deleniti tenetur.\nMaiores nostrum omnis architecto labore eum voluptas omnis rerum deserunt."
                        },
                        new
                        {
                            ID = new Guid("e05ca72e-5f91-46ac-9fc8-5572b00c7d06"),
                            CommentId = new Guid("c6c0ebbc-e61a-479a-ba27-babc4b679634"),
                            PostDate = new DateTime(2023, 4, 21, 19, 19, 56, 955, DateTimeKind.Local).AddTicks(5515),
                            Text = "perferendis"
                        },
                        new
                        {
                            ID = new Guid("a0dded82-5f95-4356-a007-e2313131788d"),
                            CommentId = new Guid("b46f35e8-162b-4dd5-ad9d-9645d3a5af0b"),
                            PostDate = new DateTime(2023, 5, 6, 12, 30, 30, 918, DateTimeKind.Local).AddTicks(8101),
                            Text = "Maiores eum sed laborum ea fugiat quis saepe. Et quam officia odio. Earum qui sunt minima ut. Eius eveniet quasi vel enim. Quisquam quia autem dolorum voluptatum ducimus non vel."
                        },
                        new
                        {
                            ID = new Guid("6a3fa97e-cac7-4c86-a9dc-cf0ce8e72db3"),
                            CommentId = new Guid("a972e1a0-6776-4f40-9973-8f91b0e66b8c"),
                            PostDate = new DateTime(2022, 12, 10, 21, 15, 19, 879, DateTimeKind.Local).AddTicks(9134),
                            Text = "Voluptas sunt quibusdam rerum est est autem omnis dolorum. Eum est voluptatum perferendis eos sit esse aut vel animi. Consequatur voluptatum ab ab impedit aut. Autem est nostrum."
                        },
                        new
                        {
                            ID = new Guid("d01b519d-1c4f-47f7-ac50-31ec62dc476f"),
                            CommentId = new Guid("986cca32-6160-4570-981d-5648e896e4ee"),
                            PostDate = new DateTime(2022, 6, 13, 13, 6, 16, 708, DateTimeKind.Local).AddTicks(9676),
                            Text = "Voluptatum voluptas error quo ut."
                        },
                        new
                        {
                            ID = new Guid("23cd32f0-3925-4d97-9160-06dd08a91970"),
                            CommentId = new Guid("8722eb57-e451-48d1-8b82-5ff767d58e17"),
                            PostDate = new DateTime(2023, 3, 14, 20, 12, 0, 968, DateTimeKind.Local).AddTicks(6639),
                            Text = "odit"
                        },
                        new
                        {
                            ID = new Guid("3edf1839-9ef2-46cd-aa10-81b50f8ab362"),
                            CommentId = new Guid("3892b4e2-369f-4184-8a88-81706960d694"),
                            PostDate = new DateTime(2022, 11, 4, 3, 5, 53, 206, DateTimeKind.Local).AddTicks(6945),
                            Text = "laboriosam"
                        },
                        new
                        {
                            ID = new Guid("089a83e2-371f-4afd-a368-b1e707da5aca"),
                            CommentId = new Guid("6d20f885-a18e-47c6-8d01-6d5241e009c1"),
                            PostDate = new DateTime(2023, 5, 11, 3, 38, 38, 347, DateTimeKind.Local).AddTicks(8242),
                            Text = "Iure consequuntur laudantium accusamus incidunt veniam aspernatur."
                        },
                        new
                        {
                            ID = new Guid("18920a16-067f-4f76-a20d-9239422c5fed"),
                            CommentId = new Guid("409e9bbf-e29c-4395-9aa4-c0d2da2bbb8d"),
                            PostDate = new DateTime(2022, 9, 1, 1, 58, 3, 242, DateTimeKind.Local).AddTicks(3101),
                            Text = "Quibusdam rem ipsa et repellat aliquid. Similique dolorem omnis rerum et praesentium dolor voluptas provident id. Nostrum beatae porro sequi."
                        },
                        new
                        {
                            ID = new Guid("370bebc3-6129-4fbf-869f-e504f41bff5a"),
                            CommentId = new Guid("dd62c50c-609d-4152-8a4a-c0edf26dbb82"),
                            PostDate = new DateTime(2022, 8, 5, 2, 28, 24, 820, DateTimeKind.Local).AddTicks(9962),
                            Text = "Eligendi unde ut quasi. Velit odio inventore magni. Nostrum reprehenderit voluptatem omnis ab aut saepe cumque alias. Vero dolore perferendis ut quo ea libero sint. Eos aliquam saepe provident repellendus ratione quidem."
                        },
                        new
                        {
                            ID = new Guid("24404c23-15ca-4ad4-8b04-d4d7666571e1"),
                            CommentId = new Guid("34ee4e3a-45d4-455a-b069-7c39a312ab08"),
                            PostDate = new DateTime(2022, 11, 7, 11, 35, 21, 906, DateTimeKind.Local).AddTicks(5825),
                            Text = "Id quibusdam aperiam vel repudiandae mollitia facere."
                        },
                        new
                        {
                            ID = new Guid("33528453-b175-4d79-bb42-f2834178d060"),
                            CommentId = new Guid("bb2400dc-75f5-438a-8c52-a81869b1d233"),
                            PostDate = new DateTime(2022, 10, 8, 18, 28, 20, 967, DateTimeKind.Local).AddTicks(597),
                            Text = "Expedita dolores velit praesentium saepe nam earum consequatur.\nMollitia rem vitae nesciunt facere tenetur eaque voluptatem.\nAlias velit incidunt suscipit tempora numquam sit itaque.\nDistinctio aut autem."
                        },
                        new
                        {
                            ID = new Guid("963cc9a1-77b4-4c4d-9d90-3a4a50097d05"),
                            CommentId = new Guid("145331a8-af26-4009-a991-1113eb656a54"),
                            PostDate = new DateTime(2023, 2, 18, 6, 29, 5, 330, DateTimeKind.Local).AddTicks(3227),
                            Text = "Quod repellendus quidem magnam quam et voluptates dolorem architecto.\nDignissimos ea amet enim soluta dicta fuga aliquid id."
                        },
                        new
                        {
                            ID = new Guid("80bc3c03-d1e9-4aa8-bb4f-e85cbb27b21c"),
                            CommentId = new Guid("e916bfb2-3621-42e2-a476-13f3d9d229af"),
                            PostDate = new DateTime(2022, 8, 2, 6, 38, 20, 971, DateTimeKind.Local).AddTicks(6801),
                            Text = "Vel accusamus est non unde nemo occaecati est veniam."
                        },
                        new
                        {
                            ID = new Guid("322fbdfe-c0d2-4435-885f-2f503fccd92f"),
                            CommentId = new Guid("1d24d398-ec78-41e2-be23-2c3de86ca8d1"),
                            PostDate = new DateTime(2023, 1, 22, 19, 21, 11, 359, DateTimeKind.Local).AddTicks(5410),
                            Text = "Culpa cum quibusdam quis ut nesciunt at eveniet qui blanditiis."
                        },
                        new
                        {
                            ID = new Guid("0f2a6c37-272f-4e12-8c9d-37c55a7deff5"),
                            CommentId = new Guid("74d3b621-020f-4ee3-976d-2118f3b777bb"),
                            PostDate = new DateTime(2023, 1, 6, 17, 33, 58, 743, DateTimeKind.Local).AddTicks(9402),
                            Text = "Reprehenderit cupiditate in voluptas dolorem amet itaque animi.\nEt autem veniam nulla qui eveniet qui voluptatem eveniet aperiam.\nVoluptatem quia rerum est corporis tempora inventore et dolores necessitatibus.\nFugiat placeat nihil aliquid quam saepe nam beatae.\nSapiente deleniti dolorem id sit consequatur aliquid."
                        });
                });

            modelBuilder.Entity("Comments.Data.Models.Feedback", b =>
                {
                    b.HasOne("Comments.Data.Models.Comment", "Comment")
                        .WithOne("Feedback")
                        .HasForeignKey("Comments.Data.Models.Feedback", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Comments.Data.Models.Reply", b =>
                {
                    b.HasOne("Comments.Data.Models.Comment", "Comment")
                        .WithMany("Replies")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Comments.Data.Models.Comment", b =>
                {
                    b.Navigation("Feedback")
                        .IsRequired();

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
